
OrdererOrgs:
  - Name: Orderer
    Domain: uni.com
    Template:
      Count: 3
PeerOrgs:
  - Name: UniversityMember
    Domain: universitymember.uni.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: PublicMember
    Domain: publicmember.uni.com
    Template:
      Count: 2
    Users:
      Count: 1
 