
version: '2'

networks:
    behave:


services:
    couchdb01:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: universitymemberpeer0_couchdb
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for uni map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "5984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer0.universitymember.uni.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb01:5984
        depends_on:
            - orderer0.uni.com
            - couchdb01

    couchdb02:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: publicmemberpeer0_couchdb
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for uni map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "6984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer0.publicmember.uni.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb02:5984
        depends_on:
            - orderer0.uni.com
            - couchdb02

    couchdb11:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: universitymemberpeer1_couchdb
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for uni map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "7984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer1.universitymember.uni.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
        depends_on:
            - orderer0.uni.com
            - couchdb11

    couchdb12:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: publicmemberpeer1_couchdb
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for uni map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "8984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer1.publicmember.uni.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
        depends_on:
            - orderer0.uni.com
            - couchdb12
