version: '2'

networks:
    behave:

services:
  universitymember-ca:
    container_name: universitymember-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: universitymember-ca
    ports:
    - 7054:7054
    networks:
      - behave
  
  


